# Generated by Django 5.2.7 on 2025-11-27 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название района')),
                ('code', models.CharField(help_text='Краткий код или аббревиатура', max_length=10, unique=True, verbose_name='Код района')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='EventImportance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50, unique=True, verbose_name='Уровень важности')),
                ('weight', models.IntegerField(help_text='Числовой вес для сортировки (например, 1 - низкий, 5 - высокий)', unique=True, verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Важность мероприятия',
                'verbose_name_plural': 'Важность мероприятий',
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='position',
            name='name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес проживания'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=50, verbose_name='Username в Telegram'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vk_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на ВК'),
        ),
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание и обязанности'),
        ),
        migrations.AddField(
            model_name='position',
            name='title',
            field=models.CharField(default='Активист', max_length=100, unique=True, verbose_name='Название должности'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.URLField(blank=True, default='https://wallpapers.com/images/hd/puss-in-boots-fencing-stance-fqjw32cfhahwv4if.png', verbose_name='Ссылка на аватарку'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.position', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.district', verbose_name='Район'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('event_type', models.CharField(choices=[('official', 'Официальное мероприятие'), ('organized', 'Организованное районное мероприятие')], default='official', max_length=20, verbose_name='Тип мероприятия')),
                ('participants_count', models.IntegerField(default=0, verbose_name='Количество участников')),
                ('importance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.eventimportance', verbose_name='Важность')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('delegate', 'Делегат'), ('volunteer', 'Волонтёр'), ('listener', 'Слушатель'), ('organizer', 'Организатор')], default='listener', max_length=50, verbose_name='Роль')),
                ('status', models.CharField(default='Завершено', max_length=50, verbose_name='Статус участия')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='users.event', verbose_name='Мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участие',
                'verbose_name_plural': 'Участия',
                'unique_together': {('user', 'event')},
            },
        ),
    ]
