# Generated by Django 5.2.7 on 2025-12-11 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_district_eventimportance_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventimportance',
            options={'ordering': ['-weight'], 'verbose_name': 'Важность мероприятия', 'verbose_name_plural': 'Важность мероприятий'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='study_work_place',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место учёбы/работы'),
        ),
        migrations.AlterField(
            model_name='event',
            name='importance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='users.eventimportance', verbose_name='Важность'),
        ),
    ]
