# Generated by Django 5.2.7 on 2025-12-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_eventimportance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department_type',
            field=models.CharField(blank=True, choices=[('apparat', 'Аппарат'), ('district', 'Районное отделение')], max_length=20, null=True, verbose_name='Тип отдела'),
        ),
    ]
