# Generated by Django 5.2.7 on 2025-12-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_department_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='study_work_place',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telegram_username',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='vk_link',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, help_text='Будет использоваться для уведомлений и восстановления пароля', max_length=254, verbose_name='Адрес электронной почты'),
        ),
    ]
