# Generated by Django 5.2.7 on 2025-12-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimportance',
            name='weight',
            field=models.IntegerField(help_text='Числовой вес для сортировки (например, 1 — низкий, 5 — высокий)', unique=True, verbose_name='Вес'),
        ),
    ]
