# Generated by Django 5.2.7 on 2025-12-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_eventimportance_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='team_photo',
            field=models.ImageField(blank=True, null=True, upload_to='district_teams/', verbose_name='Фотография команды района'),
        ),
    ]
