# Generated by Django 5.2.7 on 2025-12-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, help_text='ID пользователя в Telegram для авторизации в боте', null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
