# Generated by Django 5.2.7 on 2025-12-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('deadline', models.DateField(verbose_name='Срок')),
                ('priority', models.CharField(choices=[('mobilization', 'Мобилизация'), ('regional', 'Региональный'), ('district', 'Районный')], default='regional', max_length=20, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('in_progress', 'В работе'), ('done', 'Выполнена'), ('archived', 'Архивирована')], default='open', max_length=20, verbose_name='Статус')),
                ('created_by_username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Создана (имя пользователя ТГ)')),
                ('created_by_user_id', models.BigIntegerField(blank=True, null=True, verbose_name='Создана (ID ТГ)')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['deadline', 'priority'],
            },
        ),
    ]
