# Generated by Django 5.2.7 on 2025-12-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('mobilization', 'Мобилизация'), ('regional', 'Региональный'), ('district', 'Районный'), ('online', 'Онлайн')], default='regional', max_length=20, verbose_name='Приоритет'),
        ),
    ]
