# Generated by Django 5.2.7 on 2025-12-18 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0002_alter_task_priority'),
        ('users', '0008_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-deadline', '-created_at'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.AddField(
            model_name='task',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.district', verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='task',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата проведения'),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('mobilization', 'Мобилизация'), ('regional', 'Региональная'), ('district', 'Районная'), ('online', 'Онлайн задача'), ('help', 'Помощь')], default='district', max_length=20, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by_user_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Создана (ID пользователя ТГ)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(verbose_name='Дедлайн регистрации'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deadline'], name='tasks_app_t_deadlin_4ec637_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['type'], name='tasks_app_t_type_a5db59_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['district'], name='tasks_app_t_distric_438a43_idx'),
        ),
    ]
