# Generated by Django 5.2.7 on 2025-12-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0003_alter_task_options_remove_task_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время дедлайна'),
        ),
        migrations.AddField(
            model_name='task',
            name='event_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время проведения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(verbose_name='Дедлайн'),
        ),
    ]
