# Generated by Django 5.2.7 on 2025-12-23 23:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0004_task_deadline_time_task_event_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='users_signed_up',
            field=models.ManyToManyField(blank=True, related_name='signed_up_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Записавшиеся пользователи'),
        ),
    ]
